parsers:
  - crowdsecurity/sshd-logs
scenarios:
  - crowdsecurity/ssh-bf
  - crowdsecurity/ssh-slow-bf
  - crowdsecurity/ssh-cve-2024-6387
  - crowdsecurity/ssh-refused-conn
  - crowdsecurity/ssh-generic-test
description: "sshd support : parser and brute-force detection"
contexts:
  - crowdsecurity/bf_base
author: crowdsecurity
tags:
  - linux
  - ssh
  - bruteforce

