name: tri_de_sorciers
description: Tri de Sorciers - quiz Flutter (Android & iOS) - single-message deliverable
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.1 <3.36.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: 8.0.3
  flutter_riverpod: 2.5.1
  flutter_animate: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/questions.json
